# Generated by Django 2.0.5 on 2020-05-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('author_location', models.CharField(default='', max_length=200)),
                ('acticle_source', models.CharField(default='', max_length=200)),
                ('page_nums', models.CharField(default='', max_length=50)),
                ('summary', models.TextField(default='')),
                ('key_words', models.CharField(default='', max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
