# Generated by Django 2.0.5 on 2020-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author_location',
            field=models.TextField(default=''),
        ),
    ]
