# Generated by Django 2.0.5 on 2020-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200507_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='key_words',
            field=models.TextField(default='', max_length=200),
        ),
    ]
