# Generated by Django 2.1.7 on 2020-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200528_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '文献', 'verbose_name_plural': '文献'},
        ),
    ]
